Revert "Really minor change."
This reverts commit e0cb18e967a1fa33f29a379dde2525abf6800d88.

diff --git a/go-get-latest b/go-get-latest
--- a/go-get-latest
+++ b/go-get-latest
@@ -1,7 +1,7 @@
 #!/bin/sh -e
 
 die() {
-	echo >&2 "$0: [error] $@"
+	echo >&2 "$0: [error]" "$@"
 	exit 1
 }
 
